services:
  postgres:
    image: postgres:15
    container_name: dev-postgres
    environment:
      POSTGRES_DB: userapp_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d  # Optional: for seed data
    restart: unless-stopped

volumes:
  postgres_data: